/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital.quiz;
import static digital.quiz.Numeric.a;
import java.awt.Font;
import java.io.FileInputStream; 
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
/**
 *
 * @author Generation
 */
public class attemptQuiz extends javax.swing.JFrame {
  int a=100;
  int Counter=1;
  int numCounter=0;
  int tfCounter=0;
  int mcqsCounter=0;
    
    public attemptQuiz() {
        initComponents();
    }
    
    public int questionTypeOptions(String type){
        if(type=="Numeric")
       {
          DisplayNumeric();
           revalidate();
           repaint();
           Counter++;
            return 0;
       }
       else if(type=="MCQs"){
           
       DisplayMCQS();
           revalidate();
           repaint();
           Counter++;
            return 1;
       }
       else
       {
           DisplayTrueFalse();
           revalidate();
           repaint();
           Counter++;
           return 2;
       }
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboSelection = new javax.swing.JComboBox<>();
        jSubmit = new javax.swing.JButton();
        jSubmit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2200, 2297));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(3300, 3300));

        jPanel1.setPreferredSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, Short.MAX_VALUE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton2.setText("READ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeric", "MCQs", "TrueFalse" }));

        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jSubmit1.setText("Exit");
        jSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jComboSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSubmit1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(1271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSubmit1)))
                .addContainerGap(1700, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String type=jComboSelection.getSelectedItem().toString();
    
         questionTypeOptions(type);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
login lg=new login();
        lg.setVisible(true);
        dispose();       
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmit1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jSubmit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, FileNotFoundException, ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attemptQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attemptQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attemptQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attemptQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attemptQuiz().setVisible(true);
            }
        });
    }
    
    
     public void DisplayNumeric(){
         try {
         FileInputStream fileIn = new FileInputStream("Numeric.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
        LinkedList<Numeric> num = (LinkedList<Numeric>) in.readObject();
         in.close();
         fileIn.close();
        
         
         
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           jPanel1.add(questionLabel);
          
           JTextField Question = new JTextField(num.get(numCounter).ques.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          jPanel1.add(Question);
          
          JLabel ansLabel= new JLabel("Answer : ");
           ansLabel.setFont(new Font("Serif", Font.PLAIN, 12));
          ansLabel.setBounds(50, a+30, 300, 30);
          jPanel1.add(ansLabel);
           
          JTextField Answer = new JTextField("", 50);
            Answer.setFont(new Font("Serif", Font.PLAIN, 12));
           Answer.setBounds(100, a+30, 300, 30);
         jPanel1.add(Answer);
          revalidate();
           repaint();
           numCounter++;
         a+=100;
         
      }catch(Exception e) {
         e.printStackTrace();
      }
     }
    public void DisplayMCQS(){
     try {
         FileInputStream fileIn = new FileInputStream("MCQS.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
         LinkedList<MCQS> mcqs = (LinkedList<MCQS>) in.readObject();
         in.close();
         fileIn.close();
         
        
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           jPanel1.add(questionLabel);
           
            JTextField Question = new JTextField(mcqs.get(mcqsCounter).ques.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          jPanel1.add(Question);
           
          JLabel serial1=new JLabel("1 : ");
          serial1.setFont(new Font("Serif", Font.PLAIN, 12));
        serial1.setBounds(30, a+60, 300, 30);
          jPanel1.add(serial1);
           JRadioButton opt1=new JRadioButton("");
           JTextField text1 = new JTextField(mcqs.get(mcqsCounter).opt1.toString(), 50);
            text1.setFont(new Font("Serif", Font.PLAIN, 12));
           text1.setBounds(80, a+60, 300, 30);
        jPanel1.add(text1);
           
           
           JLabel serial2=new JLabel("2 : ");
          serial2.setFont(new Font("Serif", Font.PLAIN, 12));
        serial2.setBounds(30, a+80, 300, 30);
          jPanel1.add(serial2);
            JRadioButton opt2=new JRadioButton("");
             JTextField text2 = new JTextField(mcqs.get(mcqsCounter).opt2.toString(), 50);
            text2.setFont(new Font("Serif", Font.PLAIN, 12));
           text2.setBounds(80, a+80, 300, 30);
        jPanel1.add(text2);
            
            JLabel serial3=new JLabel("3 : ");
          serial3.setFont(new Font("Serif", Font.PLAIN, 12));
        serial3.setBounds(30, a+100, 300, 30);
           jPanel1.add(serial3);
            JRadioButton opt3=new JRadioButton("");
             JTextField text3 = new JTextField(mcqs.get(mcqsCounter).opt3.toString(), 50);
            text3.setFont(new Font("Serif", Font.PLAIN, 12));
           text3.setBounds(80, a+100, 300, 30);
        jPanel1.add(text3);
            
            JLabel serial4=new JLabel("4 : ");
          serial4.setFont(new Font("Serif", Font.PLAIN, 12));
        serial4.setBounds(30, a+120, 300, 30);
           jPanel1.add(serial4);
            JRadioButton opt4=new JRadioButton("");
             JTextField text4 = new JTextField(mcqs.get(mcqsCounter).opt4.toString(), 50);
            text4.setFont(new Font("Serif", Font.PLAIN, 12));
           text4.setBounds(80, a+120, 300, 30);
        jPanel1.add(text4);
            
           
        
           ButtonGroup bg=new ButtonGroup();
             opt1.setBounds(50, a+60, 300, 30);
             opt2.setBounds(50, a+80, 300, 30);
              opt3.setBounds(50, a+100, 300, 30);
             opt4.setBounds(50, a+120, 300, 30);
            bg.add(opt1);
            bg.add(opt2);
             bg.add(opt3);
              bg.add(opt4);
             jPanel1.add(opt1);
              jPanel1.add(opt2);
               jPanel1.add(opt3);
               jPanel1.add(opt4);
             mcqsCounter++;
            a+=200;
                       
     }catch(Exception e) {
         e.printStackTrace();
      }
    }
    public void DisplayTrueFalse(){
     try {
         FileInputStream fileIn = new FileInputStream("TrueFalse.txt");
         ObjectInputStream in = new ObjectInputStream(fileIn);
         LinkedList<trueFalse> trFa = (LinkedList<trueFalse>) in.readObject();
         in.close();
         fileIn.close();
        
         
         
         JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           jPanel1.add(questionLabel);
           
            JTextField Question = new JTextField(trFa.get(tfCounter).ques.toString(), 50);
            Question.setFont(new Font("Serif", Font.PLAIN, 12));
           Question.setBounds(150, a, 300, 30);
          jPanel1.add(Question);
           
             JRadioButton optTrue=new JRadioButton("True");
            JRadioButton optFalse=new JRadioButton("False");
          
            ButtonGroup bg=new ButtonGroup();
             optTrue.setBounds(50, a+30, 300, 30);
             optFalse.setBounds(50, a+60, 300, 30);
            bg.add(optTrue);
            bg.add(optFalse);
             jPanel1.add(optTrue);
            jPanel1.add(optFalse);
            a+=100;
            tfCounter++;
            
           
     }catch(Exception e) {
         e.printStackTrace();
      }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboSelection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmit;
    private javax.swing.JButton jSubmit1;
    // End of variables declaration//GEN-END:variables
}
