/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital.quiz;
import javax.swing.*;
import java.awt.*;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import java.awt.event.*;
import java.io.Serializable;
import java.io.*;
import java.util.LinkedList;
/**
 *
 * @author Generation
 */
public class question_generator extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form question_generator
     */
     int Counter=1;  
   int a=100;
      int b=100;
   LinkedList<Numeric> numeric_list=new LinkedList<Numeric>();
LinkedList<MCQS> mcqs_list=new LinkedList<MCQS>();
LinkedList<trueFalse> trueFalse_list=new LinkedList<trueFalse>();
 
    public question_generator() {
        initComponents();
        
    }
    
    public int typeOfQuestion(String type)
    {
      if(type=="Numeric")
       {
           printNumeric();
           revalidate();
           repaint();
           return 0;
       }
       else if(type=="MCQs"){
           
        printMCQS();
           revalidate();
           repaint();
           return 1;
       }
       else
       {
           printTrueFalse();
           revalidate();
           repaint();
           return 2;
       }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        questionComboBox = new javax.swing.JComboBox<>();
        addquestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2200, 2297));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(2200, 2297));

        jPanel1.setPreferredSize(new java.awt.Dimension(4000, 4000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select the type of the question : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(319, 3729, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(3967, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        questionComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeric", "MCQs", "True/False" }));

        addquestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addquestion.setText("Add");
        addquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addquestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(955, 955, 955))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(questionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1637, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addquestionActionPerformed
       String type=questionComboBox.getSelectedItem().toString();
    typeOfQuestion(type);
       
    }//GEN-LAST:event_addquestionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       serializeNumeric(numeric_list);
       serializeTrueFalse(trueFalse_list);
       serializeMCQS(mcqs_list);
      
        login lg=new login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question_generator().setVisible(true);
            }
        });
    }
    
    public LinkedList serializeNumeric( LinkedList numeric_list)
    {
     try{
    FileOutputStream fout=new FileOutputStream("Numeric.txt",true);  
  ObjectOutputStream out=new ObjectOutputStream(fout); 
  
  out.writeObject(numeric_list);
  out.close();
  fout.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
     return numeric_list;
    }
    public void serializeTrueFalse(LinkedList trueFalse_list)
    {
    try{
    FileOutputStream fout=new FileOutputStream("TrueFalse.txt",true);  
  ObjectOutputStream out=new ObjectOutputStream(fout); 
  
  out.writeObject(trueFalse_list);
  out.close();
  fout.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void serializeMCQS(LinkedList mcqs_list)
    {
        try{
    FileOutputStream fout=new FileOutputStream("MCQS.txt",true);  
  ObjectOutputStream out=new ObjectOutputStream(fout); 
  
  out.writeObject(mcqs_list);
  out.close();
  fout.close();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
   
    public void printNumeric()
    {
    
        
          JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           jPanel1.add(questionLabel);
          
         
           JTextField numQuestion = new JTextField("", 50);
            numQuestion.setFont(new Font("Serif", Font.PLAIN, 12));
           numQuestion.setBounds(50, a+30, 300, 30);
           jPanel1.add(numQuestion);
       
           JLabel ansLabel=new JLabel("Correct Ans : ");
          ansLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        ansLabel.setBounds(50, a+60, 300, 30);
           jPanel1.add(ansLabel);
           
           JTextField numexpectedAns = new JTextField("", 20);
            numexpectedAns.setFont(new Font("Serif", Font.PLAIN, 12));
           numexpectedAns.setBounds(130, a+60, 300, 30);
          jPanel1.add(numexpectedAns);
          
             JButton save=new JButton("SAVE");
          save.setFont(new Font("Serif", Font.PLAIN, 12));
        save.setBounds(500, a, 80, 30);
          save.addActionListener(new ActionListener(){
               public void actionPerformed(ActionEvent evt)
               {
                   
                   Numeric numeric=new Numeric(numQuestion.getText(),numexpectedAns.getText());
                   numeric_list.add(numeric);
                  //numeric.serialize();
               }
           });
           jPanel1.add(save);
           revalidate();
           repaint();
           Counter++;
           a+=120;
           
    }
     public void printMCQS()    
     {
    
        JLabel questionLabel=new JLabel("QUESTION NO. "+Counter);
          questionLabel.setFont(new Font("Serif", Font.PLAIN, 12));
        questionLabel.setBounds(50, a, 300, 30);
           jPanel1.add(questionLabel);
           
           JTextField mcqsQuestion = new JTextField("", 50);
            mcqsQuestion.setFont(new Font("Serif", Font.PLAIN, 12));
           mcqsQuestion.setBounds(50, a+30, 300, 30);
           jPanel1.add(mcqsQuestion);
           
           JLabel serial1=new JLabel("1 : ");
          serial1.setFont(new Font("Serif", Font.PLAIN, 12));
        serial1.setBounds(30, a+60, 300, 30);
           jPanel1.add(serial1);
           JRadioButton opt1=new JRadioButton("");
           JTextField text1 = new JTextField("", 50);
            text1.setFont(new Font("Serif", Font.PLAIN, 12));
           text1.setBounds(80, a+60, 300, 30);
        jPanel1.add(text1);
           
           
           JLabel serial2=new JLabel("2 : ");
          serial2.setFont(new Font("Serif", Font.PLAIN, 12));
        serial2.setBounds(30, a+80, 300, 30);
           jPanel1.add(serial2);
            JRadioButton opt2=new JRadioButton("");
             JTextField text2 = new JTextField("", 50);
            text2.setFont(new Font("Serif", Font.PLAIN, 12));
           text2.setBounds(80, a+80, 300, 30);
        jPanel1.add(text2);
            
            JLabel serial3=new JLabel("3 : ");
          serial3.setFont(new Font("Serif", Font.PLAIN, 12));
        serial3.setBounds(30, a+100, 300, 30);
           jPanel1.add(serial3);
            JRadioButton opt3=new JRadioButton("");
             JTextField text3 = new JTextField("", 50);
            text3.setFont(new Font("Serif", Font.PLAIN, 12));
           text3.setBounds(80, a+100, 300, 30);
        jPanel1.add(text3);
            
            JLabel serial4=new JLabel("4 : ");
          serial4.setFont(new Font("Serif", Font.PLAIN, 12));
        serial4.setBounds(30, a+120, 300, 30);
           jPanel1.add(serial4);
            JRadioButton opt4=new JRadioButton("");
             JTextField text4 = new JTextField("", 50);
            text4.setFont(new Font("Serif", Font.PLAIN, 12));
           text4.setBounds(80, a+120, 300, 30);
        jPanel1.add(text4);
            
           
        
           ButtonGroup bg=new ButtonGroup();
             opt1.setBounds(50, a+60, 300, 30);
             opt2.setBounds(50, a+80, 300, 30);
              opt3.setBounds(50, a+100, 300, 30);
             opt4.setBounds(50, a+120, 300, 30);
            bg.add(opt1);
            bg.add(opt2);
             bg.add(opt3);
              bg.add(opt4);
             jPanel1.add(opt1);
              jPanel1.add(opt2);
               jPanel1.add(opt3);
               jPanel1.add(opt4);
               
               
                 JButton save=new JButton("SAVE");
          save.setFont(new Font("Serif", Font.PLAIN, 12));
        save.setBounds(500, a, 80, 30);
          save.addActionListener(new ActionListener(){
               public void actionPerformed(ActionEvent evt)
               {
                  if(opt1.isSelected())
                  {
                      MCQS mcqs=new MCQS(mcqsQuestion.getText(),text1.getText(),text2.getText(),text3.getText(),text4.getText(),opt1.isSelected());
                 mcqs_list.add(mcqs);
                 //mcqs.serialize();
                  }
                  else if(opt2.isSelected())
                  {
                      MCQS mcqs=new MCQS(mcqsQuestion.getText(),text1.getText(),text2.getText(),text3.getText(),text4.getText(),opt2.isSelected());
                 mcqs_list.add(mcqs);
                  }
                  else if(opt3.isSelected())
                  {
                       MCQS mcqs=new MCQS(mcqsQuestion.getText(),text1.getText(),text2.getText(),text3.getText(),text4.getText(),opt3.isSelected());
                 mcqs_list.add(mcqs);
                  }
                  else
                  {
                  MCQS mcqs=new MCQS(mcqsQuestion.getText(),text1.getText(),text2.getText(),text3.getText(),text4.getText(),opt4.isSelected());
                 mcqs_list.add(mcqs);
                  }
               }
           });
           jPanel1.add(save);
           
           revalidate();
           repaint();
           Counter++;
           a+=230;
           
     }
     public void printTrueFalse()
     {
    
           JLabel labelQuestion=new JLabel("QUESTION NO. "+Counter);
          labelQuestion.setFont(new Font("Serif", Font.PLAIN, 12));
        labelQuestion.setBounds(50, a, 300, 30);
           jPanel1.add(labelQuestion);
           
           JTextField tfQuestion = new JTextField("", 50);
            tfQuestion.setFont(new Font("Serif", Font.PLAIN, 12));
           tfQuestion.setBounds(50, a+30, 300, 30);
          jPanel1.add(tfQuestion);
           
          
           JRadioButton optTrue=new JRadioButton("True");
            JRadioButton optFalse=new JRadioButton("False");
          
            ButtonGroup bg=new ButtonGroup();
             optTrue.setBounds(50, a+60, 300, 30);
             optFalse.setBounds(50, a+80, 300, 30);
            bg.add(optTrue);
            bg.add(optFalse);
             jPanel1.add(optTrue);
            jPanel1.add(optFalse);
            
            
             JButton save=new JButton("SAVE");
          save.setFont(new Font("Serif", Font.PLAIN, 12));
        save.setBounds(500, a, 80, 30);
          save.addActionListener(new ActionListener(){
               public void actionPerformed(ActionEvent evt)
               {
                   if(optTrue.isSelected())
                   {
                       trueFalse tf=new trueFalse(tfQuestion.getText(),optTrue.isEnabled());
                       trueFalse_list.add(tf);
                       //tf.serialize();
                   }
                   else
                   {
                   trueFalse tf=new trueFalse(tfQuestion.getText(),optFalse.isEnabled());
                         trueFalse_list.add(tf);
//tf.serialize();
                   }
               }
           });
           jPanel1.add(save);
            
           revalidate();
           repaint();
           Counter++;
           a+=150;
    
     }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addquestion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> questionComboBox;
    // End of variables declaration//GEN-END:variables
}
